# Generated by Django 5.0.3 on 2024-03-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mbti_type',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
