# Generated by Django 5.0.3 on 2024-03-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_mbti_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobdetails',
            options={'managed': True},
        ),
    ]
