# Generated by Django 5.0.3 on 2024-03-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_jobdetails_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobdetails',
            options={'managed': False},
        ),
    ]
