# Generated by Django 5.0.3 on 2024-03-28 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_jobdetails_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobdetails',
            options={'managed': True},
        ),
    ]
