# Generated by Django 5.0.3 on 2024-03-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_jobdetails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
