# Generated by Django 5.0.3 on 2024-05-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tutorial_completed',
            field=models.BooleanField(default=False),
        ),
    ]
