# Generated by Django 5.0.3 on 2024-05-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userprofile_tutorial_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tutorial_completed',
        ),
    ]
