# Generated by Django 5.0.3 on 2024-05-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_userprofile_tutorial_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'applied_jobs',
                'managed': False,
            },
        ),
    ]
